name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build_deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          ls -alh .
          ./generate_deb.sh
          ls -alh

      - name: Archive debian package as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: pymchelper.deb

  test_deb:
    runs-on: ubuntu-latest
    needs: [build_deb]
    strategy:
      matrix:
        docker-tag: ['debian:7', 'debian:8', 'debian:9', 'debian:10', 'debian:11', 'ubuntu:14.04']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deb
          path: ./

      - name: Inspect artifacts
        run: |
          ls -alh .
          dpkg-deb --contents pymchelper.deb

      - name: Test installation
        run: |
          docker run -v `pwd`:/pkg ${{ matrix.docker-tag }} /bin/sh -c "ldd --version; dpkg -i /pkg/pymchelper.deb; pld2sobp --version"