name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          ls -alh .
          ./generate_deb.sh
          ls -alh
