name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build_deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          ls -alh .
          ./generate_deb.sh
          ls -alh

      - name: Archive debian package as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: '*.deb'

  test_deb:
    runs-on: ubuntu-latest
    needs: [build_deb]
    strategy:
      matrix:
        docker-tag: ['debian:8', 'debian:9', 'debian:10', 'debian:11', 'debian:stable', 'ubuntu:14.04', 'ubuntu:16.04', 'ubuntu:18.04', 'ubuntu:20.04', 'ubuntu:21.04']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deb
          path: ./

      - name: Inspect artifacts
        run: |
          ls -alh .
          dpkg-deb --contents pymchelper.deb
          dpkg-deb --contents pymchelper_old.deb

      - name: Test installation
        run: |
          docker run -v `pwd`:/pkg ${{ matrix.docker-tag }} /bin/sh -c "ldd --version; dpkg -i /pkg/pymchelper.deb; pld2sobp --version"

  test_old_deb:
    runs-on: ubuntu-latest
    needs: [build_deb]
    strategy:
      matrix:
        docker-tag: ['debian:7', 'debian:8', 'debian:9', 'debian:10', 'debian:11', 'debian:stable', 'ubuntu:12.04', 'ubuntu:14.04', 'ubuntu:16.04', 'ubuntu:18.04', 'ubuntu:20.04', 'ubuntu:21.04']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deb
          path: ./

      - name: Inspect artifacts
        run: |
          ls -alh .
          dpkg-deb --contents pymchelper.deb

      - name: Test installation
        run: |
          docker run -v `pwd`:/pkg ${{ matrix.docker-tag }} /bin/sh -c "ldd --version; dpkg -i /pkg/pymchelper_old.deb; pld2sobp --version"

  repo_prepare:
      runs-on: ubuntu-latest
      needs: [test_deb, test_old_deb]
      steps:
      - name: Inspect deps
        run: |
          wget --quiet https://github.com/aptly-dev/aptly/releases/download/v1.4.0/aptly_1.4.0_linux_amd64.tar.gz
          tar -zxf aptly_1.4.0_linux_amd64.tar.gz
          cd aptly_1.4.0_linux_amd64
          ./aptly repo create -distribution="stable" -component="main" main
          ./aptly repo add main ../pymchelper.deb
          ./aptly publish repo main
          ls -alh ~/.aptly/public

